spring:
  application:
    name: spring-boot-jobApp

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jobportal}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Guru@2003}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8080}